version: '3'
services:
  concord:
    image: node:19.6.0-alpine
    container_name: concord
    ports:
      - "3000:3000"
    working_dir: '/concord'
    tty: true
    command: [sh, -c, "npm ci && npm run dev"]
    volumes:
      - './:/concord/'
    environment:
      HOST: 0.0.0.0
      PORT: 3000

  concord-db:
    image: postgres:13.4-alpine
    container_name: concord-db
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: concord-db
      POSTGRES_PASSWORD: root
